import {
  AD_PLACEMENTS,
  INTERSTITIAL_UNIT_IDS,
  MIN_INTERSTITIAL_GAP_MS,
  TEST_INTERSTITIAL_UNIT_IDS,
  adsAvailable,
  mayShowInterstitial,
  privacyOptionsRequired,
  resolveAdUnitId,
  type AdPlatform,
} from './policy';

const PLATFORMS: AdPlatform[] = ['android', 'ios'];

/**
 * The ad unit rules.
 *
 * Nothing here is reachable by looking at the app. A test ad and a real ad are
 * the same full-screen creative with a small "Test Ad" label, and the cost of
 * getting this wrong does not arrive as a bug report — it arrives as an AdMob
 * account suspension, weeks later, for invalid traffic generated by the
 * developer's own device. That is the same class of failure the owner boundary
 * in `attempts.test.ts` and the leak guard in `haptics.test.ts` exist for.
 */
describe('ad unit resolution', () => {
  /*
    The load-bearing one, in the dangerous direction. A build with `__DEV__`
    true is Expo Go or a development build — every impression it generates is
    invalid traffic against the account.
  */
  it('never requests a production unit from a development build', () => {
    const production = new Set(
      AD_PLACEMENTS.flatMap((placement) =>
        PLATFORMS.map((platform) => INTERSTITIAL_UNIT_IDS[placement][platform]),
      ),
    );

    for (const placement of AD_PLACEMENTS) {
      for (const platform of PLATFORMS) {
        const id = resolveAdUnitId(placement, { isDev: true, platform });
        expect(id).toBe(TEST_INTERSTITIAL_UNIT_IDS[platform]);
        // Belt and braces, and it is not redundant while the placeholders below
        // still *are* the test units: once real ids are pasted in, this is the
        // assertion that keeps them out of a dev build.
        if (!production.has(TEST_INTERSTITIAL_UNIT_IDS[platform])) {
          expect(production.has(id)).toBe(false);
        }
      }
    }
  });

  /*
    The other direction, which is invisible in the opposite way: a release build
    stuck on test units works perfectly and earns nothing at all.
  */
  it('requests the configured unit for the placement in a release build', () => {
    for (const placement of AD_PLACEMENTS) {
      for (const platform of PLATFORMS) {
        expect(resolveAdUnitId(placement, { isDev: false, platform })).toBe(
          INTERSTITIAL_UNIT_IDS[placement][platform],
        );
      }
    }
  });

  /*
    `INTERSTITIAL_UNIT_IDS` is a total `Record<AdPlacement, ...>`, so a new
    placement is a compile error until it states its ids — but a *blank* string
    satisfies the type, and an empty unit id fails at request time as a silent
    no-fill rather than as anything a reader would notice.
  */
  it('has a non-empty, well-formed id for every placement on both platforms', () => {
    for (const placement of AD_PLACEMENTS) {
      for (const platform of PLATFORMS) {
        expect(INTERSTITIAL_UNIT_IDS[placement][platform]).toMatch(
          /^ca-app-pub-\d+\/\d+$/,
        );
      }
    }
  });

  it('keeps the two placements on separate units so they can be measured apart', () => {
    // Not a style rule: one blended figure cannot tell you which of the two is
    // the one annoying people, which is the only question worth asking of them.
    // Skipped while both are still Google's shared sample unit.
    const usingPlaceholders = AD_PLACEMENTS.every((placement) =>
      PLATFORMS.some(
        (platform) =>
          INTERSTITIAL_UNIT_IDS[placement][platform] ===
          TEST_INTERSTITIAL_UNIT_IDS[platform],
      ),
    );
    if (usingPlaceholders) return;

    for (const platform of PLATFORMS) {
      const ids = AD_PLACEMENTS.map(
        (placement) => INTERSTITIAL_UNIT_IDS[placement][platform],
      );
      expect(new Set(ids).size).toBe(ids.length);
    }
  });
});

/**
 * The frequency cap.
 *
 * Every case here is one nobody can reach by hand: exercising it means sitting
 * two papers less than a minute apart on a development build, and the symptom
 * of it being wrong in the dangerous direction is not a bug report but an AdMob
 * policy strike weeks later. The opposite direction is worse to debug and just
 * as silent — a cap that never expires turns the whole ads layer off and looks
 * exactly like Google having no fill.
 */
describe('interstitial frequency cap', () => {
  const now = 1_700_000_000_000;

  it('allows the first interstitial of a session', () => {
    expect(mayShowInterstitial({ lastShownAt: null, now })).toBe(true);
  });

  /*
    The case the cap exists for. Open practice draws the whole bank and can be
    finished from the question navigator at any point, so a learner can start
    it, answer one question, finish, and meet `preExam` and `preResult` inside a
    minute.
  */
  it('suppresses a second interstitial inside the gap', () => {
    expect(mayShowInterstitial({ lastShownAt: now - 1_000, now })).toBe(false);
    expect(
      mayShowInterstitial({
        lastShownAt: now - (MIN_INTERSTITIAL_GAP_MS - 1),
        now,
      }),
    ).toBe(false);
  });

  /*
    The other half, and the one that keeps the cap from quietly becoming an
    off switch: an ordinary sitting must still show both of its ads.
  */
  it('allows one again once the gap has elapsed', () => {
    expect(
      mayShowInterstitial({ lastShownAt: now - MIN_INTERSTITIAL_GAP_MS, now }),
    ).toBe(true);
    // A three-minute quick exam, which is the shortest real paper there is.
    expect(mayShowInterstitial({ lastShownAt: now - 180_000, now })).toBe(true);
  });

  /*
    Wall time can jump backwards — a manual change, an NTP correction — leaving
    the stamp in the future. Answering "no" there would suppress every ad until
    real time caught up, which could be hours. The ads layer fails open
    everywhere else and does so here too.
  */
  it('fails open when the clock has moved backwards', () => {
    expect(mayShowInterstitial({ lastShownAt: now + 3_600_000, now })).toBe(
      true,
    );
  });

  /*
    Not a style assertion. Below about thirty seconds the cap stops covering the
    case it was written for, and a very large value silently turns the second
    placement off for every normal sitting.
  */
  it('keeps the gap in a range that is neither useless nor an off switch', () => {
    expect(MIN_INTERSTITIAL_GAP_MS).toBeGreaterThanOrEqual(30_000);
    expect(MIN_INTERSTITIAL_GAP_MS).toBeLessThanOrEqual(180_000);
  });
});

describe('platform support', () => {
  it('accepts the two platforms that ship', () => {
    expect(adsAvailable('android')).toBe(true);
    expect(adsAvailable('ios')).toBe(true);
  });

  /*
    `npm run web` is a development convenience and the Google Mobile Ads native
    module has no web implementation. Answering yes here would send a request
    into a module that is not there.
  */
  it('refuses web, where the native module does not exist', () => {
    expect(adsAvailable('web')).toBe(false);
    expect(adsAvailable('windows')).toBe(false);
  });
});

/**
 * Whether the settings screen offers a way back into the consent form.
 *
 * Every case here is unreachable from this developer's own device, which is
 * what earns the tests: the status is `NOT_REQUIRED` everywhere outside the EEA
 * and UK, so the branch that matters — the one that keeps the app compliant and
 * keeps the promise its privacy policy already makes — is the branch that never
 * fires in Iraq, and never fires in Expo Go either, where the SDK is absent and
 * every answer is `UNKNOWN`. Reaching it by hand means a debug geography and a
 * development build.
 */
describe('the consent control', () => {
  /*
    The load-bearing direction. `REQUIRED` is what a user who has answered the
    form in a regulated region reports, and Google obliges the publisher to keep
    a control that re-presents it. Hiding the row there is a compliance failure
    that is invisible from inside the app — ads keep serving and nothing
    complains.
  */
  it('offers the control where the consent form is required', () => {
    expect(privacyOptionsRequired('REQUIRED')).toBe(true);
  });

  /*
    The common case, and the reason the row is hidden rather than disabled: for
    most of this app's audience the form does not exist, so a permanently
    present row would open nothing. Same call the biometric-lock card makes.
  */
  it('hides it where consent was never required', () => {
    expect(privacyOptionsRequired('NOT_REQUIRED')).toBe(false);
  });

  /*
    `UNKNOWN` is Expo Go, web, and the window before `initialiseAds` settles.
    Treating it as required would put a dead row on the settings screen of every
    device in the project's own documented development workflow.
  */
  it('hides it before the SDK has an answer', () => {
    expect(privacyOptionsRequired('UNKNOWN')).toBe(false);
    expect(privacyOptionsRequired(null)).toBe(false);
    expect(privacyOptionsRequired(undefined)).toBe(false);
    expect(privacyOptionsRequired('')).toBe(false);
  });

  /*
    The status crosses the native bridge as a string, so it is an arbitrary
    value rather than a member of the enum the types claim. A version testing
    for "not NOT_REQUIRED" would answer yes to every one of these — which is the
    plausible way to write this check, and it is wrong in the direction that
    puts a dead control in front of everybody.
  */
  it('treats an unrecognised status as no control rather than as a yes', () => {
    for (const status of ['required', 'Required', 'OBTAINED', 'garbage']) {
      expect(privacyOptionsRequired(status)).toBe(false);
    }
  });
});
