import {
  AD_PLACEMENTS,
  INTERSTITIAL_UNIT_IDS,
  TEST_INTERSTITIAL_UNIT_IDS,
  adsAvailable,
  resolveAdUnitId,
  type AdPlatform,
} from './policy';

const PLATFORMS: AdPlatform[] = ['android', 'ios'];

/**
 * The ad unit rules.
 *
 * Nothing here is reachable by looking at the app. A test ad and a real ad are
 * the same full-screen creative with a small "Test Ad" label, and the cost of
 * getting this wrong does not arrive as a bug report — it arrives as an AdMob
 * account suspension, weeks later, for invalid traffic generated by the
 * developer's own device. That is the same class of failure the owner boundary
 * in `attempts.test.ts` and the leak guard in `haptics.test.ts` exist for.
 */
describe('ad unit resolution', () => {
  /*
    The load-bearing one, in the dangerous direction. A build with `__DEV__`
    true is Expo Go or a development build — every impression it generates is
    invalid traffic against the account.
  */
  it('never requests a production unit from a development build', () => {
    const production = new Set(
      AD_PLACEMENTS.flatMap((placement) =>
        PLATFORMS.map((platform) => INTERSTITIAL_UNIT_IDS[placement][platform]),
      ),
    );

    for (const placement of AD_PLACEMENTS) {
      for (const platform of PLATFORMS) {
        const id = resolveAdUnitId(placement, { isDev: true, platform });
        expect(id).toBe(TEST_INTERSTITIAL_UNIT_IDS[platform]);
        // Belt and braces, and it is not redundant while the placeholders below
        // still *are* the test units: once real ids are pasted in, this is the
        // assertion that keeps them out of a dev build.
        if (!production.has(TEST_INTERSTITIAL_UNIT_IDS[platform])) {
          expect(production.has(id)).toBe(false);
        }
      }
    }
  });

  /*
    The other direction, which is invisible in the opposite way: a release build
    stuck on test units works perfectly and earns nothing at all.
  */
  it('requests the configured unit for the placement in a release build', () => {
    for (const placement of AD_PLACEMENTS) {
      for (const platform of PLATFORMS) {
        expect(resolveAdUnitId(placement, { isDev: false, platform })).toBe(
          INTERSTITIAL_UNIT_IDS[placement][platform],
        );
      }
    }
  });

  /*
    `INTERSTITIAL_UNIT_IDS` is a total `Record<AdPlacement, ...>`, so a new
    placement is a compile error until it states its ids — but a *blank* string
    satisfies the type, and an empty unit id fails at request time as a silent
    no-fill rather than as anything a reader would notice.
  */
  it('has a non-empty, well-formed id for every placement on both platforms', () => {
    for (const placement of AD_PLACEMENTS) {
      for (const platform of PLATFORMS) {
        expect(INTERSTITIAL_UNIT_IDS[placement][platform]).toMatch(
          /^ca-app-pub-\d+\/\d+$/,
        );
      }
    }
  });

  it('keeps the two placements on separate units so they can be measured apart', () => {
    // Not a style rule: one blended figure cannot tell you which of the two is
    // the one annoying people, which is the only question worth asking of them.
    // Skipped while both are still Google's shared sample unit.
    const usingPlaceholders = AD_PLACEMENTS.every((placement) =>
      PLATFORMS.some(
        (platform) =>
          INTERSTITIAL_UNIT_IDS[placement][platform] ===
          TEST_INTERSTITIAL_UNIT_IDS[platform],
      ),
    );
    if (usingPlaceholders) return;

    for (const platform of PLATFORMS) {
      const ids = AD_PLACEMENTS.map(
        (placement) => INTERSTITIAL_UNIT_IDS[placement][platform],
      );
      expect(new Set(ids).size).toBe(ids.length);
    }
  });
});

describe('platform support', () => {
  it('accepts the two platforms that ship', () => {
    expect(adsAvailable('android')).toBe(true);
    expect(adsAvailable('ios')).toBe(true);
  });

  /*
    `npm run web` is a development convenience and the Google Mobile Ads native
    module has no web implementation. Answering yes here would send a request
    into a module that is not there.
  */
  it('refuses web, where the native module does not exist', () => {
    expect(adsAvailable('web')).toBe(false);
    expect(adsAvailable('windows')).toBe(false);
  });
});
